name: Merge to Main

on:
  push:
    branches:
      - stage

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to Main
        run: |
          git config user.name "Your Name"
          git config user.email "your-email@example.com"
          git fetch origin main
          git checkout -b main origin/main
          git merge --no-ff ${{ github.event.ref }}

      - name: Push changes
        run: |
          git push origin main
